### ISSUE TITLE
DDD: Chapter 4 ドメインを隔離する

### ISSUE THREAD

**Issue by takayukioda** [givery-technology/reading-articles#2]
# 4章 ドメインを隔離する

https://hackmd.io/WC2dKK6qR3y_QDVbGUJG8Q

**Comment by task-k0414** [comment]
@TsubasaK111 
こちらに資料貼ってくだし〜

**Comment by task-k0414** [comment]
レイヤー化アーキテクチャ
---

- API - ビジネスロジックを含む
  - インフラ (DB)
  - ドメイン
- SAP - ビジネスロジックを含まない
  - アプリケーション
  - UI

利口な UI 「アンチパターン」
---

疑問

- そもそも「利口なUI」とはなにか？
- アンチパターンになる場合とそうでない場合はとはどういう場合か？
