### ISSUE TITLE
DDD: Chapter 5  ソフトウェアで表現されたモデル

### ISSUE THREAD

**Issue by takayukioda** [givery-technology/reading-articles#3]

**Comment by task-k0414** [comment]
関連
---

関連を扱いやすくする方法
1. 関連をたどる方法を強制する （なんとなくわかる
2. 限定子を付加して、多重度を効果的に減らす (わからん ~限定子ってなんだ~
3. 本質的ではない関連を除去する （わかる

関係性はできる限り限定すべし

限定された関係性

![figure 5.1](https://i.gyazo.com/53dea3f235c964264104699f8b2ebec9.png)

限定子とは、任意の時点において大統領は一人に "限定されている" 状態における "時点" のような factor のこと

![figure 5.2](https://i.gyazo.com/b83ad709f87e8c37c5cf297a0441e47e.png)

「1個の「証券取引口座」が1個の株式に対応している」:thinking:
